DEFINE DATABASE CICD_DEMO{{db_suffix}};

DEFINE SCHEMA CICD_DEMO{{db_suffix}}.RAW;
DEFINE SCHEMA CICD_DEMO{{db_suffix}}.ANALYTICS;
DEFINE SCHEMA CICD_DEMO{{db_suffix}}.SERVE;

DEFINE WAREHOUSE CICD_DEMO_WH_{{env}}
WITH
    WAREHOUSE_SIZE = '{{wh_size}}'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;
