CREATE DATABASE IF NOT EXISTS CICD_DEMO{{db_suffix}};

CREATE SCHEMA IF NOT EXISTS CICD_DEMO{{db_suffix}}.RAW;
CREATE SCHEMA IF NOT EXISTS CICD_DEMO{{db_suffix}}.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS CICD_DEMO{{db_suffix}}.SERVE;

CREATE WAREHOUSE IF NOT EXISTS CICD_DEMO_WH_{{env}}
WITH
    WAREHOUSE_SIZE = '{{wh_size}}'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;
