CREATE OR ALTER TABLE CICD_DEMO{{db_suffix}}.RAW.CUSTOMERS (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255),
    REGION VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CHANGE_TRACKING = TRUE;

CREATE OR ALTER TABLE CICD_DEMO{{db_suffix}}.RAW.ORDERS (
    ORDER_ID NUMBER,
    CUSTOMER_ID NUMBER NOT NULL,
    ORDER_DATE DATE NOT NULL,
    ORDER_AMOUNT NUMBER(12,2) NOT NULL,
    STATUS VARCHAR(50) DEFAULT 'PENDING',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CHANGE_TRACKING = TRUE;

CREATE OR ALTER TABLE CICD_DEMO{{db_suffix}}.RAW.PRODUCTS (
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    CATEGORY VARCHAR(100),
    UNIT_PRICE NUMBER(10,2)
)
CHANGE_TRACKING = TRUE;
