DEFINE DYNAMIC TABLE CICD_DEMO{{db_suffix}}.ANALYTICS.ORDER_SUMMARY
    WAREHOUSE = CICD_DEMO_WH_{{env}}
    TARGET_LAG = '1 hour'
AS
SELECT 
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.REGION,
    COUNT(o.ORDER_ID) AS TOTAL_ORDERS,
    SUM(o.ORDER_AMOUNT) AS TOTAL_REVENUE,
    AVG(o.ORDER_AMOUNT) AS AVG_ORDER_VALUE,
    MAX(o.ORDER_DATE) AS LAST_ORDER_DATE,
    MIN(o.ORDER_DATE) AS FIRST_ORDER_DATE
FROM CICD_DEMO{{db_suffix}}.RAW.CUSTOMERS c
LEFT JOIN CICD_DEMO{{db_suffix}}.RAW.ORDERS o ON c.CUSTOMER_ID = o.CUSTOMER_ID
GROUP BY c.CUSTOMER_ID, c.CUSTOMER_NAME, c.REGION;

DEFINE DYNAMIC TABLE CICD_DEMO{{db_suffix}}.ANALYTICS.REGIONAL_SALES
    WAREHOUSE = CICD_DEMO_WH_{{env}}
    TARGET_LAG = 'DOWNSTREAM'
AS
SELECT 
    c.REGION,
    COUNT(DISTINCT c.CUSTOMER_ID) AS CUSTOMER_COUNT,
    COUNT(o.ORDER_ID) AS ORDER_COUNT,
    SUM(o.ORDER_AMOUNT) AS TOTAL_REVENUE,
    AVG(o.ORDER_AMOUNT) AS AVG_ORDER_VALUE
FROM CICD_DEMO{{db_suffix}}.RAW.CUSTOMERS c
LEFT JOIN CICD_DEMO{{db_suffix}}.RAW.ORDERS o ON c.CUSTOMER_ID = o.CUSTOMER_ID
GROUP BY c.REGION;
