CREATE OR REPLACE VIEW CICD_DEMO{{db_suffix}}.SERVE.V_CUSTOMER_ORDERS AS
SELECT 
    os.CUSTOMER_ID,
    os.CUSTOMER_NAME,
    os.REGION,
    os.TOTAL_ORDERS,
    os.TOTAL_REVENUE,
    os.AVG_ORDER_VALUE,
    os.LAST_ORDER_DATE,
    DATEDIFF('day', os.LAST_ORDER_DATE, CURRENT_DATE()) AS DAYS_SINCE_LAST_ORDER,
    CASE 
        WHEN os.TOTAL_REVENUE >= 50000 THEN 'Platinum'
        WHEN os.TOTAL_REVENUE >= 25000 THEN 'Gold'
        WHEN os.TOTAL_REVENUE >= 10000 THEN 'Silver'
        ELSE 'Bronze'
    END AS CUSTOMER_TIER
FROM CICD_DEMO{{db_suffix}}.ANALYTICS.ORDER_SUMMARY os;

CREATE OR REPLACE VIEW CICD_DEMO{{db_suffix}}.SERVE.V_REGIONAL_DASHBOARD AS
SELECT 
    rs.REGION,
    rs.CUSTOMER_COUNT,
    rs.ORDER_COUNT,
    rs.TOTAL_REVENUE,
    rs.AVG_ORDER_VALUE,
    ROUND(rs.TOTAL_REVENUE / NULLIF(rs.CUSTOMER_COUNT, 0), 2) AS REVENUE_PER_CUSTOMER
FROM CICD_DEMO{{db_suffix}}.ANALYTICS.REGIONAL_SALES rs;
