DEFINE ROLE CICD_DEMO_{{env}}_READ;
DEFINE ROLE CICD_DEMO_{{env}}_WRITE;

GRANT USAGE ON DATABASE CICD_DEMO{{db_suffix}} TO ROLE CICD_DEMO_{{env}}_READ;
GRANT USAGE ON SCHEMA CICD_DEMO{{db_suffix}}.RAW TO ROLE CICD_DEMO_{{env}}_READ;
GRANT USAGE ON SCHEMA CICD_DEMO{{db_suffix}}.ANALYTICS TO ROLE CICD_DEMO_{{env}}_READ;
GRANT USAGE ON SCHEMA CICD_DEMO{{db_suffix}}.SERVE TO ROLE CICD_DEMO_{{env}}_READ;

GRANT SELECT ON ALL TABLES IN SCHEMA CICD_DEMO{{db_suffix}}.RAW TO ROLE CICD_DEMO_{{env}}_READ;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA CICD_DEMO{{db_suffix}}.ANALYTICS TO ROLE CICD_DEMO_{{env}}_READ;
GRANT SELECT ON ALL VIEWS IN SCHEMA CICD_DEMO{{db_suffix}}.SERVE TO ROLE CICD_DEMO_{{env}}_READ;

GRANT USAGE ON WAREHOUSE CICD_DEMO_WH_{{env}} TO ROLE CICD_DEMO_{{env}}_READ;

GRANT ROLE CICD_DEMO_{{env}}_READ TO ROLE CICD_DEMO_{{env}}_WRITE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA CICD_DEMO{{db_suffix}}.RAW TO ROLE CICD_DEMO_{{env}}_WRITE;
